// The NSIS script for the Append HMI Web installer (scripts/dist-win.mjs).
//
// It installs the unpacked app and a Start menu and desktop shortcut to the
// launcher. Per machine, it also adds a Windows Firewall rule letting other
// computers reach the web server on private and domain networks (never
// public ones). A running copy is stopped first.

import {nsisString, windowsFileName, fourPartVersion, COMPRESSION} from '../studio/src/main/publish/NsisScript.js';

// opts: productName, version, publisher, exeName, scope ('machine'|'user'),
// compression ('small'|'fast'), outFile, appDir, rootEntries and resources
// ([{name, dir}]), firewallRule (its name), installerIcon, join,
// estimatedSizeKb
export function buildWebNsis(opts)
{
	const q = nsisString;
	const join = opts.join;
	const machine = opts.scope === 'machine';
	const root = machine ? 'HKLM' : 'HKCU';
	const id = windowsFileName(opts.productName);
	const rule = q(opts.firewallRule);
	const lines = [];
	const add = (...l) => lines.push(...l);

	add('; Generated by npm run dist-win',
		'Unicode true',
		'ManifestDPIAware true',
		`!define PRODUCT "${q(opts.productName)}"`,
		`!define EXE "${q(opts.exeName)}"`,
		`!define UNINST_KEY "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${q(id)}"`,
		'Name "${PRODUCT}"',
		`OutFile "${q(opts.outFile)}"`,
		`RequestExecutionLevel ${machine ? 'admin' : 'user'}`,
		`InstallDir "${machine ? '$PROGRAMFILES64' : '$LOCALAPPDATA\\Programs'}\\${q(id)}"`,
		`InstallDirRegKey ${root} "\${UNINST_KEY}" "InstallLocation"`,
		COMPRESSION[opts.compression] || COMPRESSION.small,
		...(opts.installerIcon ? [`Icon "${q(opts.installerIcon)}"`, `UninstallIcon "${q(opts.installerIcon)}"`] : []),
		'ShowInstDetails nevershow',
		'ShowUninstDetails nevershow',
		'',
		`VIProductVersion "${fourPartVersion(opts.version)}"`,
		'VIAddVersionKey "ProductName" "${PRODUCT}"',
		`VIAddVersionKey "ProductVersion" "${q(opts.version)}"`,
		`VIAddVersionKey "FileVersion" "${q(opts.version)}"`,
		'VIAddVersionKey "FileDescription" "${PRODUCT} Setup"',
		`VIAddVersionKey "CompanyName" "${q(opts.publisher)}"`,
		`VIAddVersionKey "LegalCopyright" "${q(opts.publisher)}"`,
		'',
		'Page instfiles',
		'UninstPage uninstConfirm',
		'UninstPage instfiles',
		'',
		// Stops the app, its helpers and hmi-comms, and waits up to 10 s
		'!macro StopApp',
		'  nsExec::Exec \'"$SYSDIR\\taskkill.exe" /F /T /IM "${EXE}"\'',
		'  Pop $0',
		'  StrCpy $1 0',
		'  stop_wait:',
		'  nsExec::Exec \'cmd /c tasklist /FI "IMAGENAME eq ${EXE}" /NH | find /I "${EXE}"\'',
		'  Pop $0',
		'  StrCmp $0 "0" 0 stop_gone',
		'  IntOp $1 $1 + 1',
		'  IntCmp $1 20 stop_gone',
		'  Sleep 500',
		'  Goto stop_wait',
		'  stop_gone:',
		'  Sleep 1000',
		'!macroend',
		'',
		'Function .onInit',
		'  SetRegView 64',
		machine ? '  SetShellVarContext all' : '  SetShellVarContext current',
		'FunctionEnd',
		'',
		'Function un.onInit',
		'  SetRegView 64',
		machine ? '  SetShellVarContext all' : '  SetShellVarContext current',
		'FunctionEnd',
		'',
		'Section "Install"',
		'  !insertmacro StopApp',
		'  RMDir /r "$INSTDIR\\resources"',
		'  RMDir /r "$INSTDIR\\locales"',
		'  SetOutPath "$INSTDIR"');

	for (const e of opts.rootEntries)
	{
		if (e.name === 'resources')
		{
			continue;
		}

		add(e.dir ? `  File /r "${q(join(opts.appDir, e.name))}"` : `  File "${q(join(opts.appDir, e.name))}"`);
	}

	add('  SetOutPath "$INSTDIR\\resources"');

	for (const e of opts.resources)
	{
		add(e.dir ? `  File /r "${q(join(opts.appDir, 'resources', e.name))}"` :
			`  File "${q(join(opts.appDir, 'resources', e.name))}"`);
	}

	add('  SetOutPath "$INSTDIR"',
		'  WriteUninstaller "$INSTDIR\\Uninstall.exe"',
		'  CreateShortcut "$SMPROGRAMS\\${PRODUCT}.lnk" "$INSTDIR\\${EXE}"',
		'  CreateShortcut "$DESKTOP\\${PRODUCT}.lnk" "$INSTDIR\\${EXE}"',
		...(machine ? [
			'',
			// Replaced, not added again, on an upgrade
			`  nsExec::Exec 'netsh advfirewall firewall delete rule name="${rule}"'`,
			'  Pop $0',
			`  nsExec::Exec 'netsh advfirewall firewall add rule name="${rule}" dir=in action=allow ` +
				'program="$INSTDIR\\${EXE}" enable=yes profile=private,domain\'',
			'  Pop $0'] : []),
		'',
		`  WriteRegStr ${root} "\${UNINST_KEY}" "DisplayName" "\${PRODUCT}"`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "DisplayVersion" "${q(opts.version)}"`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "Publisher" "${q(opts.publisher)}"`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "DisplayIcon" "$INSTDIR\\\${EXE}"`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "InstallLocation" "$INSTDIR"`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "UninstallString" '"$INSTDIR\\Uninstall.exe"'`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "QuietUninstallString" '"$INSTDIR\\Uninstall.exe" /S'`,
		`  WriteRegDWORD ${root} "\${UNINST_KEY}" "NoModify" 1`,
		`  WriteRegDWORD ${root} "\${UNINST_KEY}" "NoRepair" 1`,
		`  WriteRegDWORD ${root} "\${UNINST_KEY}" "EstimatedSize" ${Math.max(0, Math.round(opts.estimatedSizeKb || 0))}`,
		'SectionEnd',
		'',
		'Function .onInstSuccess',
		'  IfSilent done',
		'  MessageBox MB_YESNO|MB_ICONQUESTION "Start ${PRODUCT} now?" IDNO done',
		'  Exec \'"$INSTDIR\\${EXE}"\'',
		'  done:',
		'FunctionEnd',
		'',
		'Section "Uninstall"',
		'  !insertmacro StopApp',
		'  Delete "$SMPROGRAMS\\${PRODUCT}.lnk"',
		'  Delete "$DESKTOP\\${PRODUCT}.lnk"',
		'  RMDir /r "$INSTDIR\\resources"',
		'  RMDir /r "$INSTDIR\\locales"',
		'  Delete "$INSTDIR\\*.*"',
		'  RMDir "$INSTDIR"',
		// Shortcuts the launcher made for projects stay: they belong to the user
		...(machine ? [`  nsExec::Exec 'netsh advfirewall firewall delete rule name="${rule}"'`, '  Pop $0'] : []),
		`  DeleteRegKey ${root} "\${UNINST_KEY}"`,
		'SectionEnd',
		'');

	return lines.join('\n');
}
